# This file is licensed under the terms of the MIT license. See the file
# "LICENSE" in the project root for more information.
#
# This module was developed by Daren Thomas at the assistant chair for
# Sustainable Architecture and Building Technologies (Suat) at the Institute of
# Technology in Architecture, ETH Zuerich. See http://suat.arch.ethz.ch for
# more information.

import pandas as pd

r"""
esoreader.py

A python module for reading \*.eso files generated by EnergyPlus

The eso files generated by EnergyPlus contains a data dictionary, which
describes the values reported by EnergyPlus. The list of values reported
depends on the simulation input file, specifically the Output:Variable
objects. EnergyPlus can output the same variable at different
frequencies and for different "keys", which are for instance surfaces or
equipment names.

Following the data dictionary is a list of output variable values for
each of the configured variable coordinates.

The output of the esoreader module is therefore a data dictionary object
that contains a mapping of variable "coordinates" (grouping of reporting
frequency, key and variable name) to the index used by EnergyPlus and a
data object, which essentially just maps that index to the timeseries
data.

Example
=======

New interface:

    import esoreader
    PATH_TO_ESO = r'/Path/To/EnergyPlus/Output/eplusout.eso'
    eso = esoreader.read_from_path(PATH_TO_ESO)
    df = eso.to_frame('total heat loss energy')  #  pandas.DataFrame


Old interface: (still works)
::

    import esoreader

    PATH_TO_ESO = r'/Path/To/EnergyPlus/Output/eplusout.eso'
    dd, data = esoreader.read(PATH_TO_ESO)
    frequency, key, variable = dd.find_variable(
        'Zone Ventilation Total Heat Loss Energy')[0]
    idx = dd.index[frequency, key, variable]
    time_series = data[idx]
"""


class DataDictionary:
    def __init__(self, version: str | None = None, timestamp: str | None = None):
        """
        variables = dict of ids, int => [reporting_frequency,
                                         key, variable, unit]

        index = dict {(key, variable, reporting_frequency) => id)}
        """
        self.version: str | None = version
        self.timestamp: str | None = timestamp
        self.variables: dict[int, list[str | None]] = {}
        self.index: dict[tuple[str, str | None, str], int] = {}

    def build_index(self):
        """builds a reverse index for finding ids."""
        for var_id, (frequency, key, name, unit) in self.variables.items():
            self.index[(frequency, key, name)] = var_id

    def find_variable(self, search: str) -> list[tuple[str, str | None, str]]:
        """returns the coordinates (timestep, key, variable_name) in the
        data dictionary that can be used to find an index. The search is case
        insensitive."""
        return [
            (freq, key, name)
            for (freq, key, name) in self.index.keys()
            if search.lower() in name.lower()
        ]

    def __repr__(self) -> str:
        return f"<DataDictionary version={self.version} timestamp={self.timestamp} variables={len(self.variables)}>"


class EsoFile:

    def __init__(self, eso_file):
        self.eso_file = eso_file
        self.dd = self._read_data_dictionary()
        self.dd.build_index()
        self.data: dict[int, list[float]] = self._read_data()

    def find_variable(
        self, search: str, key: str | None = None, frequency: str = "TimeStep"
    ) -> list[tuple[str, str | None, str]]:
        """returns the coordinates (timestep, key, variable_name) in the
        data dictionary that can be used to find an index. The search is case
        insensitive and need only be specified partially."""
        variables = self.dd.find_variable(search)

        # Only filter by frequency if provided
        if frequency is not None:
            variables = [v for v in variables if v[0].lower() == frequency.lower()]

        # Only filter by key if provided
        if key is not None:
            variables = [v for v in variables if v[1] and v[1].lower() == key.lower()]

        return variables

    def to_frame(
        self,
        search: str,
        key: str | None = None,
        frequency: str = "TimeStep",
        index: list | None = None,
        use_key_for_columns: bool = True,
    ) -> pd.DataFrame:
        """
        creates a pandas DataFrame objects with a column for every variable
        that matches the search pattern and key. An None key matches all keys.
        NOTE: The frequency *has* to be the same for all variables selected.
        (uses find_variable to select the variables)
        """
        variables = self.find_variable(search, key=key, frequency=frequency)
        if use_key_for_columns:
            data = {v[1]: self.data[self.dd.index[v]] for v in variables}
        else:
            data = {v[2]: self.data[self.dd.index[v]] for v in variables}
        df = pd.DataFrame(data)
        if index is not None:
            df.index = index
        return df

    def to_series(
        self, search: str, key: str | None = None, frequency: str = "TimeStep"
    ) -> pd.Series:
        """
        Returns a pandas Series for the first variable matching the search.
        """
        variables = self.find_variable(search, key=key, frequency=frequency)
        if not variables:
            raise ValueError(f"No variable found for search: {search}")
        var = variables[0]
        return pd.Series(self.data[self.dd.index[var]])

    def _read_reporting_frequency(self, line: str) -> tuple[str, str | None]:
        if "! " in line:
            line = line.split("! ")[0]
        if " !" in line:
            line, freq = line.split(" !")
            freq = freq.split()[0]
            return line, freq
        return line, None

    def _read_variable_unit(self, variable: str) -> tuple[str, str | None]:
        if "[" in variable:
            variable, unit = variable.split("[")
            return variable.strip(), unit.rstrip("]")
        return variable, None

    def _read_data_dictionary(self) -> DataDictionary:
        """parses the head of the eso_file, returning the data dictionary.
        the file object eso_file is advanced to the position needed by
        read_data.
        """
        version, timestamp = [
            s.strip() for s in self.eso_file.readline().split(",")[-2:]
        ]
        dd = DataDictionary(version, timestamp)
        line = self.eso_file.readline().strip()
        while line != "End of Data Dictionary":
            line, freq = self._read_reporting_frequency(line)
            if freq:
                fields = [f.strip() for f in line.split(",")]
                try:
                    if len(fields) >= 4:
                        var_id, _, key, name = fields[:4]
                    else:
                        var_id, _, name = fields[:3]
                        key = None
                    name, unit = self._read_variable_unit(name)
                    dd.variables[int(var_id)] = [freq, key, name, unit]
                except ValueError:
                    pass  # skip malformed lines
            line = self.eso_file.readline().strip()
        dd.ids = set(dd.variables.keys())
        return dd

    def _read_data(self) -> dict[int, list[float]]:
        """parse the data from the .eso file returning,
        NOTE: eso_file should be the same file object that was passed to
        read_data_dictionary(eso_file) to obtain dd."""
        data = {var_id: [] for var_id in self.dd.variables}
        for line in self.eso_file:
            if line.startswith("End of Data"):
                break
            fields = [f.strip() for f in line.split(",")]
            try:
                var_id = int(fields[0])
                if var_id in self.dd.variables:
                    data[var_id].append(float(fields[1]))
            except (ValueError, IndexError):
                continue
        return data

    def __repr__(self) -> str:
        return f"<EsoFile version={self.dd.version} variables={len(self.dd.variables)}>"


def read_from_path(eso_file_path: str) -> EsoFile:
    """
    read in a .eso file and return an EsoFile object that can be used
    to read in pandas DataFrame and Series objects.
    """
    with open(eso_file_path, "r") as eso_file:
        eso = EsoFile(eso_file)
    return eso


def read(eso_file_path: str) -> tuple[DataDictionary, dict[int, list[float]]]:
    """Read in an .eso file and return the data dictionary and a dictionary
    representing the data.
    NOTE: this function is here for backward compatibilty reasons. Use
    read_from_path() instead to obtain an EsoFile object.
    """
    eso = read_from_path(eso_file_path)
    return eso.dd, eso.data
